apiVersion: v1
baseDomain: lp.int
compute:
- hyperthreading: Disabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Disabled
  name: master
  replicas: 3
metadata:
  name: asocp42test
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: ''
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCi3SzsYv4bUZbJb/qrDfVvAtf/6cmmMQ3YL5DWh3hy0nz6tJTSRFzgaYFFAlC0FuFgeAK0LIsyim7OLVdlpG5gkqNo0TwQYFuhhugBLKBRdK3A4HY/bgZGIvXrPonJv/9zmorCBDZmWwtPJHzZbpk1+8j/I7wvTAkCkiZZy8IlQAk8TAM05Oku8/UqWjaqdpCLaoFgKC3kXBk603GKcXVuBj142rv1H9AeZr8ofZlhKyyZaoMbZt0bDGKqH1TB+ciLsPMzZkP+2jBzC34GLZowvDlaJdNOE7a0aNXCwCRyEzfKwQCoITfi/SuNLc2mX8FvF2IjjZFKQHi1ojgiMB+p root@astestans01'
