---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    CLUSTER_NAME: "{{ cluster_name }}"
    DOMAIN_NAME: "{{ domain_name }}"
    START_ADDR: "{{ start_addr }}"
    END_ADDR: "{{ end_addr }}"
    HAPROXYIP:  "{{ haproxyip }}"

  tasks:
    - name: inc variables 
      include_vars: myvars.yaml
    - name: configure hosts
      include_role:
        name: bertvv.hosts
      vars:
        hosts_entries:
          - name: "apps.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}" 
            ip: "{{ HAPROXYIP }}"
          - name: "{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}"
            ip: "{{ HAPROXYIP }}"
    - name: configure dnsmasq
      include_role:
        name: bertvv.dnsmasq
      vars:
        dnsmasq_domain: "{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}"
        dnsmasq_interface:  eth1
        dnsmasq_dhcp_ranges:
          - start_addr: "{{ START_ADDR }}"
            end_addr: "{{ END_ADDR }}"
            lease_time: '8h'
        dnsmasq_srv_hosts:
          - name: "_etcd-server-ssl._tcp.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}"
            target: etcd-0.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}
            port: 2380
            priority: 0
            weight: 10
          - name: "_etcd-server-ssl._tcp.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}"
            target: etcd-1.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}
            port: 2380
            priority: 0
            weight: 10
          - name: "_etcd-server-ssl._tcp.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}"
            target: etcd-2.{{ CLUSTER_NAME }}.{{ DOMAIN_NAME }}
            port: 2380
            priority: 0
            weight: 10
    - name : Addlines for pxeboot to dnsmasq
      lineinfile:  
        path: /etc/dnsmasq.conf
        line: pxe-service=x86PC, "install coreos", pxelinux
        state: present
    - name : Addlines for pxeboot to dnsmasq
      lineinfile:
        path: /etc/dnsmasq.conf
        line: enable-tftp
        state: present
    - name : Addlines for pxeboot to dnsmasq
      lineinfile:
        path: /etc/dnsmasq.conf
        line: tftp-root=/var/lib/tftpboot
        state: present

    - name : Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted 

    - name : install tftp
      yum:
        name: tftp-server
        state: 'present'
        update_cache: 'yes'
    - name: create folder
      file:
        path: /var/lib/tftpboot/boot
        state: directory
        mode: 0755
    - name: copy files
      copy:
        src: /usr/lib/syslinux/bios/pxelinux.0
        dest: /var/lib/tftpboot
        mode: 0755
      with_fileglob: files/*
    - name: copy boot images
      copy:
        src: /usr/lib/syslinux/bios/ldlinux.c32
        dest: /var/lib/tftpboot/boot
        mode: 0755
      with_fileglob: files/boot/*
    - name: create folder
      file:
        path: /var/lib/tftpboot/pxelinux.cfg/hosts
        state: directory
        mode: 0755
